"""Render exhaustive ``Literal`` stubs for Rust-style sized integer types.

Not imported at runtime by :mod:`types_bits`. See ``python -m types_bits --help``.
"""

from __future__ import annotations

import os
from typing import TYPE_CHECKING, Final, Literal, NamedTuple, assert_never

from types_bits._spec import MAX_BITS

if TYPE_CHECKING:
    from collections.abc import Iterable
    from pathlib import Path


class Unsigned(NamedTuple):
    """A ``uN`` width.

    >>> Unsigned(8).name, Unsigned(8).lo, Unsigned(8).hi
    ('u8', 0, 255)
    """

    bits: int

    @property
    def name(self) -> str:
        return f"u{self.bits}"

    @property
    def lo(self) -> int:
        return 0

    @property
    def hi(self) -> int:
        return (1 << self.bits) - 1


class Signed(NamedTuple):
    """An ``iN`` width, two's complement.

    >>> Signed(8).name, Signed(8).lo, Signed(8).hi
    ('i8', -128, 127)
    >>> Signed(1).lo, Signed(1).hi
    (-1, 0)
    """

    bits: int

    @property
    def name(self) -> str:
        return f"i{self.bits}"

    @property
    def lo(self) -> int:
        return -(1 << (self.bits - 1))

    @property
    def hi(self) -> int:
        return (1 << (self.bits - 1)) - 1


type Width = Unsigned | Signed

type Variant = Literal["flat", "nested", "union", "annotated", "opaque"]
type Kind = Literal["both", "u", "i"]

VARIANTS: Final[tuple[Variant, ...]] = ("flat", "nested", "union", "annotated", "opaque")
KINDS: Final[tuple[Kind, ...]] = ("both", "u", "i")

BANNER: Final = "# Generated by types_bits._generate — do not edit."


def members(width: Width) -> range:
    """Every value the width can hold.

    >>> tuple(members(Signed(2)))
    (-2, -1, 0, 1)
    """
    return range(width.lo, width.hi + 1)


def narrower(width: Width) -> Width | None:
    """Step down one bit, keeping the signedness; ``None`` at the floor.

    >>> narrower(Unsigned(3)), narrower(Unsigned(1))
    (Unsigned(bits=2), None)
    """
    if width.bits == 1:
        return None
    match width:
        case Unsigned():
            return Unsigned(width.bits - 1)
        case Signed():
            return Signed(width.bits - 1)
        case _ as unreachable:  # pyright: ignore[reportUnnecessaryComparison]
            assert_never(unreachable)


def added(width: Width) -> tuple[int, ...]:
    """Take the members a width contributes over the next-narrower one.

    >>> added(Unsigned(3))
    (4, 5, 6, 7)
    >>> added(Signed(3))
    (-4, -3, 2, 3)
    """
    prev = narrower(width)
    if prev is None:
        return tuple(members(width))
    return tuple(value for value in members(width) if value not in members(prev))


def widths(bits: int, kind: Kind = "both") -> tuple[Width, ...]:
    """Widen from one bit up to ``bits``, unsigned before signed.

    >>> tuple(w.name for w in widths(2))
    ('u1', 'u2', 'i1', 'i2')
    """
    unsigned = tuple(Unsigned(n) for n in range(1, bits + 1))
    signed = tuple(Signed(n) for n in range(1, bits + 1))
    match kind:
        case "both":
            return unsigned + signed
        case "u":
            return unsigned
        case "i":
            return signed


def _literal(values: Iterable[int]) -> str:
    return f"Literal[{', '.join(map(str, values))}]"


def _rhs(width: Width, variant: Variant) -> str:
    prev = narrower(width)
    match variant:
        case "flat":
            return _literal(members(width))
        case "nested":
            if prev is None:
                return _literal(members(width))
            return f"Literal[{prev.name}, {', '.join(map(str, added(width)))}]"
        case "union":
            if prev is None:
                return _literal(members(width))
            return f"{prev.name} | {_literal(added(width))}"
        case "annotated":
            return f"Annotated[{_literal(members(width))}, Ge({width.lo}), Le({width.hi})]"
        case "opaque":
            return "int"


def alias(width: Width, variant: Variant) -> str:
    """Render one PEP 695 alias statement.

    >>> alias(Unsigned(2), "flat")
    'type u2 = Literal[0, 1, 2, 3]'
    >>> alias(Signed(2), "union")
    'type i2 = i1 | Literal[-2, 1]'
    >>> alias(Unsigned(1), "annotated")
    'type u1 = Annotated[Literal[0, 1], Ge(0), Le(1)]'
    """
    return f"type {width.name} = {_rhs(width, variant)}"


def _imports(variant: Variant) -> tuple[str, ...]:
    match variant:
        case "flat" | "nested" | "union":
            return ("from typing import Literal",)
        case "annotated":
            return ("from typing import Annotated, Literal", "from annotated_types import Ge, Le")
        case "opaque":
            return ()


def _dunder_all(names: Iterable[str]) -> str:
    return f"__all__ = [{', '.join(f'{name!r}' for name in names)}]"


def module(bits: int, variant: Variant = "flat", kind: Kind = "both") -> str:
    """Render a whole stub module.

    >>> print(module(1, kind="u"))
    # Generated by types_bits._generate — do not edit.
    # variant=flat bits=1 kind=u
    <BLANKLINE>
    from typing import Literal
    <BLANKLINE>
    __all__ = ['u1']
    <BLANKLINE>
    type u1 = Literal[0, 1]
    <BLANKLINE>
    """
    selected = widths(bits, kind)
    sections = (
        (BANNER, f"# variant={variant} bits={bits} kind={kind}"),
        _imports(variant),
        (_dunder_all([width.name for width in selected]),),
        tuple(alias(width, variant) for width in selected),
    )
    return "\n\n".join("\n".join(section) for section in sections if section) + "\n"


def write(path: Path, bits: int = MAX_BITS, variant: Variant = "flat", kind: Kind = "both") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    scratch = path.with_name(f"{path.name}.{os.getpid()}.tmp")
    scratch.write_text(module(bits, variant, kind), encoding="utf-8")
    scratch.replace(path)
    return path
